version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - ci
      - github-actions
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    labels:
      - pip
      - dependencies
